export const GET_ERRORS = "GET_ERRORS";
export const USER_LOGIN="USER_LOGIN";
export const GET_TOTAL_USERS="GET_TOTAL_USERS";
export const GET_ACTIVE_TRAINEES="GET_ACTIVE_TRAINEES";
export const GET_ACTIVE_TRAINERS="GET_ACTIVE_TRAINERS";
export const GET_BLOCK_TRAINEES="GET_BLOCK_TRAINEES";
export const GET_BLOCK_TRAINERS="GET_BLOCK_TRAINERS";